name: Build Test Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        run: echo "Building..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Testing
        run: echo "Testing..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploying
        run: echo "Deploying..."

  verify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify Workflow
        run: echo "Workflow executed successfully!"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
