name: Build Test Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building..."

      - name: Test
        run: echo "Testing..."

      - name: Deploy
        run: echo "Deploying..."

      - name: Verify
        run: echo "Workflow executed successfully!"
